apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  labels:
    app: adminer
spec:
  # externalTrafficPolicy: Cluster # comment out this to use ingress instead of service
  # type: LoadBalancer # use extenal IP
  type: NodePort # use NAT inside k8s
  # clusterIP: None
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
