apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga-deployment
  labels:
    app: konga
spec:
  # replicas: 3 # number of pods need to create
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      hostNetwork: false
      containers:
      - name: konga
        image: pantsel/konga:0.14.9
        imagePullPolicy: Always # 當有新的映像檔更新時會自動去拉映像檔的功能
        ports:
        - containerPort: 1338
        env:
        - name: DB_ADAPTER
          value: postgres
        - name: DB_DATABASE
          value: kong
        - name: DB_HOST
          value: postgres-service
        - name: DB_PASSWORD
          value: kong
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: kong
        - name: NODE_ENV
          value: jimcondition
