apiVersion: v1
kind: Service
metadata:
  name: kong-service
  labels:
    app: kong
spec:
  # externalTrafficPolicy: Cluster # comment out this to use ingress instead of service
  # type: LoadBalancer # use extenal IP
  type: NodePort # use NAT inside k8s
  # clusterIP: None
  selector:
    app: kong
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: admin-port
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: reverse-port