apiVersion: apps/v1
# apiVersion: extensions/v1beta1 # 舊版使用
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  # replicas: 3 # number of pods need to create
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostNetwork: false # 
      containers:
      - name: postgres
        image: postgres:9.6
        imagePullPolicy: Always # 當有新的映像檔更新時會自動去拉映像檔的功能
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: kong
        - name: POSTGRES_USER
          value: kong
        - name: POSTGRES_PASSWORD
          value: kong
