version: "3"
services:
  web:
    image:  nginx:1.13.7
    container_name: web
    # ports:
    #   - 80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy-network

  cdn:
    image:  openbridge/nginx:1.15.3 # since origin nginx image didn't contains module `ngx_cache_purge`
    container_name: cdn
    ports:
      - "80:80"
    volumes:
      - ./cdn_nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy-network

  varnish:
    image: varnish:6.3.1
    container_name: varnish
    # ports:
    #   - 80
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
      - cache_vol:/var/lib/varnish
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge

volumes:
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs