apiVersion: v1
kind: Service
metadata:
  name: nats1
  labels:
    app: nats1
spec:
  selector:
    app: nats1
  # type: LoadBalancer # use extenal IP
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
  - name: metrics
    port: 7777
  - name: leafnodes
    port: 7422
  - name: gateways
    port: 7522