version: "3"
services:
  web:
    image:  nginx:1.13.7
    container_name: web
    ports:
      - "80:80"
    volumes:
      # put index.html in folder html would mount into conatiner
      - ./html:/usr/share/nginx/html
      # put default.conf in folder conf would moutn into ...
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # put nginx.conf outside
      # - ./nginx.conf:/etc/nginx/nginx.conf
      # mount ssl
      # - ./ssl:/etc/nginx/ssl
      # mount nginx logs
      # - ./log:/var/log/nginx
    networks:
      - proxy-network
  cdn:
    image:  openbridge/nginx:1.15.3 # since origin nginx image didn't contains module `ngx_cache_purge`
    container_name: cdn
    ports:
      - "8080:80"
    volumes:
      # put index.html in folder html would mount into conatiner
      # - ./html:/usr/share/nginx/html
      # put default.conf in folder conf would moutn into ...
      - ./cdn_nginx.conf:/etc/nginx/nginx.conf
      # put nginx.conf outside
      # - ./nginx.conf:/etc/nginx/nginx.conf
      # mount ssl
      # - ./ssl:/etc/nginx/ssl
      # mount nginx logs
      # - ./log:/var/log/n
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
