version: "3.1"

services:
  nginx:
    container_name: nginx
    image: nginx:1.13.7
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./default.conf:/etc/nginx/conf.d/default.conf

