version: "3"
services:
  nginx_openresty:
    container_name: openresty
    # image: openresty/openresty:1.9.15.1-trusty
    image: openresty/openresty # 2020/03/03 - 1.15.8.2
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      # - ./lua:/usr/local/openresty/nginx/lua:ro
    networks:
      - proxy-network

  redis-commander:
    container_name: redis-commander
    networks:
      - proxy-network
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      # - REDIS_HOSTS=redis:redis:6379:0:yourpassword
      - REDIS_HOSTS=redis:redis:6379:0
    ports:
      - "8081:8081"

  redis:
    container_name: redis
    # command: redis-server --requirepass yourpassword
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - proxy-network


networks:
  proxy-network:
    driver: bridge