apiVersion: v1
kind: ConfigMap
metadata:
  name: stan1-config
data:
  stan.conf: |
    port: 4222
    
    # open while need a http port for monitor
    http_port: 8222
    
    cluster {
      listen: 0.0.0.0:6222
      routes: [
        "nats-route://stan2:6222",
        "nats-route://stan3:6222",
      ]
    }
    
    streaming {
      id: stan
      store: file
      dir: storea
      cluster {
        node_id: "stan1"
        peers: ["stan2", "stan3"]
      }
      # store options
      store_limits {
        max_channels: 0 # 不限制最大的 channel 數
        max_subs: 0 # 不限制最大的訂閱數
        max_msgs: 0 # 不限制在每個channel內的最大訊息量
        max_bytes: 0 # 不限制在每個channel內的訊息最大容量
        max_age: "48h" # 限制每個訊息在channel內的最大存在時間(預設持久不限)
        max_inactivity: "1h" # 當channel沒有任一的訂閱者時，能夠存在的最大時效
      }
    }
    
    authorization {
      user: "stan"
      pass: "stan"
    }
    
    # pid file: store pid
    # pid_file: "nats_streaming.pid"
    
    
    # logging options
    debug:   true # false on production
    # debug:   false
    # trace:   true # false on production
    trace:   false
    # logtime: true # log(true) or fmt(false) on golang
    logtime: true
    # log_file: "node.log"