apiVersion: v1
kind: ConfigMap
metadata:
  name: stan2-config
data:
  stan.conf: |
    port: 4222
    http: 8222

    streaming {
     ns: "nats://nats1.nats.svc.cluster.local:4222,nats://nats2.nats.svc.cluster.local:4222,nats://nats3.nats.svc.cluster.local:4222"

     id: stan
     cluster_id: stan
     store: file
     dir: /data/stan/store
     cluster {
       node_id: $POD_NAME
       log_path: /data/stan/log
       # Explicit names of resulting peers
       peers: ["stan1", "stan2", "stan3"]
       store_limits {
         max_channels: 0 # 不限制最大的 channel 數
         max_subs: 0 # 不限制最大的訂閱數
         max_msgs: 0 # 不限制在每個channel內的最大訊息量
         max_bytes: 0 # 不限制在每個channel內的訊息最大容量
         max_age: "24h" # 限制每個訊息在channel內的最大存在時間(預設持久不限)
         max_inactivity: "24h" # 當channel沒有任一的訂閱者時，能夠存在的最大時效
       }
      }
    }