apiVersion: v1
kind: Service
metadata:
  name: stan2
  labels:
    app: stan2
spec:
  # type: LoadBalancer # use extenal IP
  clusterIP: None
  selector:
    app: stan2
  ports:
  - name: metrics
    port: 7777