# Use root/secret as user/password credentials
version: '3.1'

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      # MongoDB server
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_IP_ADDRESS}
      # MongoDB port
      ME_CONFIG_MONGODB_PORT: ${MONGO_DB_EXPOSE_PORT} # default 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}

