apiVersion: v1
kind: Service
metadata:
  name: stan3
  labels:
    app: stan3
spec:
  # type: LoadBalancer # use extenal IP
  clusterIP: None
  selector:
    app: stan3
  ports:
  - name: monitor
    port: 8222
  - name: routes
    port: 6222
  - name: client
    port: 4222