filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /tmp/access.log
  json.keys_under_root: true
  json.overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  pipeline: geoip
  username: "elastic"
  password: "changeme"
  indices:
    - index: "geo-pipeline-template"


processors:
- add_cloud_metadata: ~