apiVersion: v1
kind: Service
metadata:
  name: redis1
  labels:
    app: redis1
spec:
  # type: NodePort # use NAT inside k8s
  clusterIP: None # 不使用NAT IP
  # type: LoadBalancer # use extenal IP
  # type: NodePort # use NAT inside k8s
  selector:
    app: redis1
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

