# https://github.com/elastic/kibana-docker
# FROM docker.elastic.co/kibana/kibana:7.2.1
FROM docker.elastic.co/kibana/kibana:7.9.1

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
RUN kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.0/enhanced-table-1.13.0_7.9.1.zip
