version: "3"
services:

  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=influx
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"



