apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis5
  labels:
    app: redis5
spec:
  selector:
    matchLabels:
      app: redis5
  template:
    metadata:
      labels:
        app: redis5
    spec:
      hostNetwork: false # 
      containers:
      - name: redis5
        image: redis:latest
        imagePullPolicy: Always # 當有新的映像檔更新時會自動去拉映像檔的功能
        # args: ["--requirepass", "yourpassword"]
        command:
          - "redis-server"
        args: 
          # - "--requirepass"
          # - "yourpassword"
          - "--cluster-enabled"
          - "yes"
          - "--appendonly"
          - "yes"
          - "--bind"
          - "0.0.0.0"
        ports:
        - containerPort: 6379
