version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: docker_zookeeper_kafka
    build: .
    command: zookeeper-server-start.sh /tmp/zookeeper.properties
    ports:
      - "2181:2181"

  kafka1:
    container_name: kafka1
    image: docker_zookeeper_kafka
    build: .
    command: kafka-server-start.sh /tmp/server1.properties
    ports:
      - "9091:9091"

  kafka2:
    container_name: kafka2
    image: docker_zookeeper_kafka
    build: .
    command: kafka-server-start.sh /tmp/server2.properties
    ports:
      - "9092:9092"

  kafka3:
    container_name: kafka3
    image: docker_zookeeper_kafka
    build: .
    command: kafka-server-start.sh /tmp/server3.properties
    ports:
      - "9093:9093"

