version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.13.7
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /tmp:/tmp
    networks:
      - proxy-network

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.9.1
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /tmp:/tmp
    networks:
      - proxy-network

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - proxy-network
    restart: always

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - proxy-network
    depends_on:
      - elasticsearch
    restart: always


networks:
  proxy-network:
    driver: bridge
