version: "3"
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - proxy-network

  prometheus:
    container_name: prometheus
    image: quay.io/prometheus/prometheus:latest
    ports:
     - 9090:9090
    volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
