# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  # - job_name: 'arangodb'
  #   metrics_path: '/_admin/metrics'
  #   basic_auth:
  #       username: 'root'
  #       password: 'openSesame'
  #   static_configs:
  #     - targets: ['arangodb:8529']
 
  - job_name: 'arangodb1'
    metrics_path: '/_admin/metrics'
    static_configs:
      - targets: ['192.168.51.188:8551']
 
  - job_name: 'arangodb2'
    metrics_path: '/_admin/metrics'
    static_configs:
      - targets: ['192.168.51.188:8552']
 
  - job_name: 'arangodb3'
    metrics_path: '/_admin/metrics'
    static_configs:
      - targets: ['192.168.51.188:8553']
 