version: "3"
services:
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      mysql:
        ipv4_address: 192.18.0.100

  m1:
    image: mysql:5.7
    container_name: m1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      # - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./mysql/m1.cnf:/etc/mysql/my.cnf
    networks:
      mysql:
        ipv4_address: 192.18.0.2

  s1:
    image: mysql:5.7
    container_name: s1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/s1.cnf:/etc/mysql/my.cnf
    networks:
      mysql:
        ipv4_address: 192.18.0.3
    depends_on:
      - m1
    links:
      - m1

  s2:
    image: mysql:5.7
    container_name: s2
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/s2.cnf:/etc/mysql/my.cnf
    networks:
      mysql:
        ipv4_address: 192.18.0.4
    depends_on:
      - m1
    links:
      - m1

  m2:
    image: mysql:5.7
    container_name: m2
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      # - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./mysql/m2.cnf:/etc/mysql/my.cnf
    networks:
      mysql:
        ipv4_address: 192.18.0.5

  s3:
    image: mysql:5.7
    container_name: s3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./mysql/s3.cnf:/etc/mysql/my.cnf
    networks:
      mysql:
        ipv4_address: 192.18.0.6
    depends_on:
    - m2
    links:
    - m2

  s4:
    image: mysql:5.7
    container_name: s4
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./mysql/s4.cnf:/etc/mysql/my.cnf
    networks:
      mysql:
        ipv4_address: 192.18.0.7
    depends_on:
    - m2
    links:
    - m2

  mycat:
    build: ./mycat
    container_name: mycat
    volumes:
      - ./mycat/conf/server.xml:/home/mycat/conf/server.xml
      - ./mycat/conf/schema.xml:/home/mycat/conf/schema.xml
      - ./mycat/conf/rule.xml:/home/mycat/conf/rule.xml
    ports:
      - "8066:8066"
      - "9066:9066"
    networks:
      mysql:
        ipv4_address: 192.18.0.8
    links:
      - m1
      - s1
      - s2
      - m2
      - s3
      - s4

networks:
  mysql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.18.0.0/24
