version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./player:/usr/share/nginx/html

  httpflv:
    image: mailbyms/http-flv
    container_name: httpflv
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - ./logs:/usr/local/nginx/logs
      - ./data:/data
    ports:
      - 1935:1935
      - 9090:9090
      - 8002:8002

