# apiVersion: v1
# kind: Service
# metadata:
#   name: redis-headless-server
#   namespace: redis-cluster
#   labels:
#     app: redis-cluster-app
# spec:
#   ports:
#   - name: redis-port
#     port: 6379
#   clusterIP: None
#   selector:
#     app: redis-cluster-app

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-cluster
  labels:
    app: redis-cluster-app
spec:
  # type: LoadBalancer # use extenal IP
  clusterIP: None
  ports:
  - name: redis-port
    protocol: "TCP"
    port: 6379
    targetPort: 6379
  selector:
    app: redis-cluster-app