apiVersion: v1
kind: Service
metadata:
  name: stan1
  labels:
    app: stan1
spec:
  # type: LoadBalancer # use extenal IP
  clusterIP: None
  selector:
    app: stan1
  ports:
  - name: metrics
    port: 7777